<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<title>default.vbprj</title>
<meta http-equiv="content-type" content="text/html;charset=utf-8" />

<link href="ABCD/styles_urw4m.css" type="text/css" rel="stylesheet"/>

<style type="text/css">
body {
	background-image: url(ABCD/back.jpg);
}

</style>

<style type="text/css">A#vbUL_urw4ma{display:none}</style>

</head>
<body>
<div align="center">
<script type="text/javascript"> var vbImgPath=""</script>
<script type="text/javascript" src="ABCD/scurw4m.js"></script>
<a id="vbUL_urw4ma" href="http://vista-buttons.com">Button For Web Page by Vista-Buttons.com v4.5.0</a>
</div>

</body>
</html>